# Generated by Django 5.0.2 on 2024-02-29 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='smartfon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('img_url', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('ram', models.IntegerField()),
                ('memory', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('data', models.DateField()),
            ],
        ),
    ]
