# Generated by Django 5.0.2 on 2024-03-01 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartfon',
            name='memory',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='smartfon',
            name='ram',
            field=models.CharField(max_length=255),
        ),
    ]
