# Generated by Django 5.0.2 on 2024-03-01 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_smartfon_memory_alter_smartfon_ram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartfon',
            name='memory',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='smartfon',
            name='ram',
            field=models.IntegerField(),
        ),
    ]
